### ISSUE TITLE
`time_open_days` is incorrect for Gitlab Issues

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#1008]
The field `time_open_days` is incorrect based on the description at the [gitlab_issues schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/gitlab_issues.csv)

The description says "Time open in days" which is coherent with the field name, but in reality the stored value is calculated as a difference of the last update time and the creation time. In other words, the calculation is static and is updated only if any modification is done to the ticket/issue.

As a result, a ticket created 100 days ago with a single modification/update done 99 days ago will offer a value of **1** while the correct value today should be **100**.

**Comment by zhquan** [comment]
@sanacl - I see that the difference is calculated between `created_at` and `now` (https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/gitlab.py#L170) and you are right it will update the field `time_open_days` only if it has any update. We have to calculate this field using `scripted fields`.

We have `painless_time_open` field on [gittlab merge requests](https://github.com/chaoss/grimoirelab-sigils/blob/master/json/gitlab_merge_requests-index-pattern.json). We should add this same field on gitlab issues.
