### ISSUE TITLE
[aoc] Refreshing identities process doesn't work

### ISSUE THREAD

**Issue by dlumbrer** [chaoss/grimoirelab-elk#1031]
The refreshing process of the identities in the areas of code index does not work.

What happened:

- The first time the enriched index is created for areas of code, the identities are created and well saved.
- If you update a profile the refreshing index does not work (maybe does not trigger)
- Then the profile updated is not refreshed in the enriched index not showing the update in the dashboard.

**Comment by zhquan** [comment]
I close the issue if you see this error again please reopen it. Thank you very much.

Best,
Quan
