### ISSUE TITLE
[question/p2o.py] disabling parts of GitHub enrichment 

### ISSUE THREAD

**Issue by m-oss-1** [chaoss/grimoirelab-elk#1041]
Hi, I've started working with GrimoireELK to create a enriched dataset for a project. The enrichment process is taking too much time due the quantity of items in the selected repositories. My question is if it have an option to disable the enrichment of the extra information about commits, because the metrics I've selected to make my study will not use the enriched data from this part.

**Comment by jjmerchante** [comment]
You can use only Perceval to collect only the commits, or in case you want to store the commits in Elastic, you can use sirmordred with `enrich = False` in the configuration file.

**Comment by sduenas** [comment]
p2o is deprecated. Closing this issue.
