### ISSUE TITLE
Field with the author name in github2_pull_requests index

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#1063]
When looking for the author of a review in the index `github2_pull_requests` what field do we have to use? I read at https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github2_pull_requests.csv

* author_name: Pull request author name from SortingHat profile.
* user_data_name: Pull request author name from SortingHat profile.

Can you please confirm they contain the same information

**Comment by zhquan** [comment]
@sanacl yes they contain the same information
