### ISSUE TITLE
Add git_author_domain to enriched data in Areas of Code study

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-elk#174]
In the Areas of Code study a field like the one added to GrimoireELK enriched must be added:

https://github.com/grimoirelab/GrimoireELK/commit/8956866d9347dad91258aad2fe4f143ad6c3b1d9

**Comment by alpgarcia** [comment]
Feature added in: https://github.com/dicortazar/ceres/pull/15

Support for that feature here added by: #241

**Comment by alpgarcia** [comment]
@acs should we close this?

**Comment by acs** [comment]
All integrates now!
