### ISSUE TITLE
ImportError: No module named 'grimoire_elk.panels' 

### ISSUE THREAD

**Issue by innovationchef** [chaoss/grimoirelab-elk#217]
I followed the [installation doc](https://grimoirelab.gitbooks.io/tutorial/content/before-you-start/installing-grimoirelab.html) and got everything running on my system. I am trying to run an example given in doc to [create a simple dashboard](https://grimoirelab.gitbooks.io/tutorial/content/grimoireelk/a-simple-dashboard.html) but I am getting this ImportError error while trying to build the dashboard by 
`kidash.py --elastic_url-enrich http://127.0.0.1:9200 --import /tmp/git-dashboard.json` 

I checked the repository and it seems that the file panel.py has been removed in [this commit](https://github.com/chaoss/grimoirelab-elk/commit/67ebae548fd1338623b968325602b6e2ae8cb4b0#diff-a2cbc462c388a26fa914db16b803d771).

**Comment by jgbarah** [comment]
This is due to a change in the name of the package that I had not reflected in the tutorial. Sorry about that. I just updated it.

The current name of the package is `kidash` (not `grimoirelab-kidash`), and the name of the program (once the package is installed) is also `kidash` (instead of `kidash.py`). So, create a fresh virtual environment, and in it run:

```
pip install kidash
kidash --elastic_url-enrich http://127.0.0.1:9200 --import /tmp/git-dashboard.json
``` 

Let me know if that doesn't work, please.

**Comment by innovationchef** [comment]
This is what I am getting now - 
```
$ kidash --elastic_url-enrich http://127.0.0.1:9200 --import /tmp/git-dashboard.json
2018-02-16 14:00:33,490 Panel not found (not in directory, no panels module): /tmp/git-dashboard.json
2018-02-16 14:00:33,491 Wrong file format (can't find 'dashboard' field): /tmp/git-dashboard.json

```

**Comment by jgbarah** [comment]
Do you have a file `/tmp/git-dashboard.json`? The first message you get suggests you don't...

**Comment by innovationchef** [comment]
I don't have that file. Shouldn't have it been created after I executed the the first two commands - `p2o.py --enrich --index git_raw --index-enrich git -e http://127.0.0.1:9200 --no_inc --debug git https://github.com/grimoirelab/GrimoireELK.git ?

**Comment by innovationchef** [comment]
Okay, so it was my mistake. I copied the git-dashboard.json is a wrong tmp direactory. I can see the dashboard now. Thanks.
