### ISSUE TITLE
Add gender support in the identities module in GELK

### ISSUE THREAD

**Issue by dicortazar** [chaoss/grimoirelab-elk#218]
According to chaoss/grimoirelab#69, there is a need to support gender in the GrimoireLab toolchain. And grimoirelab-elk is one of the pieces of this toolchain.

With this respect, this task expects as outcome to have an update in the identities module where GELK asks SortingHat through the API about certain aspects of the community member.

This is just an initial requirements, so further discussion could be part of this ticket.

**Comment by sduenas** [comment]
Gender was merged by #240 . Closing this issue.
