### ISSUE TITLE
unable to create indexes in ElasticSearch

### ISSUE THREAD

**Issue by venky18** [chaoss/grimoirelab-elk#219]
I am following the commands mentioned in the [docs](https://grimoirelab.gitbooks.io/tutorial/grimoireelk/a-simple-dashboard.html) 
```
$ p2o.py --enrich --index git_raw --index-enrich git \
  -e http://localhost:9200 --no_inc --debug \
  git https://github.com/grimoirelab/perceval.git

$ p2o.py --enrich --index git_raw --index-enrich git \
  -e http://localhost:9200 --no_inc --debug \
  git https://github.com/grimoirelab/GrimoireELK.git
```

the output I should get
![elasticsearch-index](https://user-images.githubusercontent.com/9168631/36441308-363f484a-1698-11e8-9f75-e605fcff1117.png)
the output I am getting
![screenshot from 2018-02-20 23-49-07](https://user-images.githubusercontent.com/9168631/36441464-c1ecac70-1698-11e8-9830-de612f2ff9ae.png)
there is no index in data. How can i resolve this issue?
I am using `docker run -d -p 9200:9200 -p 5601:5601 nshou/elasticsearch-kibana` to run elasticsearch and kibana

**Comment by valeriocos** [comment]
@venky18 sorry for the late reply. Were you able to solve this issue?

The difference in the ouput is due to a different version of ES (the first image is ES 2.x, while the last one is ES >5.x). Recently we have migrated ELK to ES 5.1.1, thus now the expected output is the one you were getting.
