### ISSUE TITLE
Removal of the code that generates the "conf" index

### ISSUE THREAD

**Issue by hmitsch** [chaoss/grimoirelab-elk#221]
**Desirement Source:** 
https://github.com/mozilla/participation-metrics-org/issues/157

**Short Description:**
A vulnerability assessment conducted by [Mozilla's Enterprise Information Security](http://infosec.mozilla.org/) team revealed, that
> https://analytics.mozilla.community/elasticsearch/conf/_search leaks some configuration data eg:
"git command - fatal: could not create leading directories of '/home/bitergia/.perceval/repositories/https://github.com/MozillaFoundation/Design.git-git'\n"

**Potential Solution:**
According to @acs:
> This data is not used anymore. Is legacy stuff that must be removed. 

/cc @gdestuynder @sanacl

**Comment by acs** [comment]
@hmitsch once https://github.com/chaoss/grimoirelab-elk/pull/243 gets accepted the index won't be created anymore. And it is safe to remove it from the current deployments.

**Comment by valeriocos** [comment]
better late than never, closing this issue since fixed by #243
