### ISSUE TITLE
[elk] Identify unused fields

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-elk#252]
In order to clean indices, it would be good to have a list of those fields not used by panels in [grimoirelab-sigils](https://github.com/chaoss/grimoirelab-sigils).

To achieve this, a quick way would be using [owlwatch tool](https://github.com/chaoss/grimoirelab-sigils/tree/master/src/owlwatch) to [compare mappings against panels](https://github.com/chaoss/grimoirelab-sigils/tree/master/src/owlwatch#mapping-vs-panel).

**Comment by dicortazar** [comment]
Closing this as duplicated from #283
