### ISSUE TITLE
Add aggregatable fields and index name to CSV Schema definition

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-elk#284]
[Moved from https://github.com/chaoss/grimoirelab-sigils/issues/144]

From https://github.com/chaoss/grimoirelab-sigils/issues/117:
>* CSV files needs a way to define when text fields should be aggregatable. By default all fields are aggregatable by default except text fields. I added a workaround considering that in our current CSVs, text implies being aggregatable. This should be removed when CSVs are improved.
>* CSV files are not specifying index names. As a workaround, I used file name without file extension for this.

**Comment by dicortazar** [comment]
Closing this as duplicated from #283
