### ISSUE TITLE
[enriched] Wrong affiliation assumptions 

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#350]
I've discovered the following information in a git enriched index I've generated with GrimoireLab environment (I am hiding name and username part of the email due to privacy concerns):
```
Author:  D...s <d...s@intel.com>
Author_domain:
Author_name: D...s
Author_org_name: Google, Inc.
git_author_domain: intel.com
```

In SortingHat database, both Intel and Google Inc. organizations are set up, and their domains are recorded too (`intel.com` for Intel and `google.com` and `chromium.org` for Google Inc.).

I think that saying `@intel.com` commits are "Google Inc." commits, is a bug.

I've a little research in the index and `D...s` has done commits with the following _unique identities_:
1.- `D...s <d...s@intel.com>`
2.- `D...s <d...@....de>`
3.- `D...s <d...t@chromium.org>`

![auto-affiliation-issue-3](https://user-images.githubusercontent.com/1178305/40063952-c7f93d6a-585e-11e8-8e89-37d651f4dd17.jpg)

So, there are 3 potential "affiliations" for `D...s` (without checking any other source):
* Intel (< 2014-06) (Organization associated with `@intel.com`)
* Unknown (2014-06 < x < 2017-12)
* Google (2017-06 < x) (Organization associated with `@chromium.org`)

But only Google Inc. is used to enrich commit data from `D...s`.

I've checked which other git commit domains have been used for people affiliated to `Google Inc.` in my index, and this is the output (there are some company domains from Intel, Opera, Samsung, etc.):
![auto-affiliation-issue-4](https://user-images.githubusercontent.com/1178305/40064332-93ffe40e-585f-11e8-8305-596ea8117160.jpg)

Wouldn't it be nice if enrichment phase takes the right information to enrich commits activity, at least?

**Comment by valeriocos** [comment]
@jsmanrique do you have some conf files/memories to replicate this issue? If not, we can check with the data we have in prd, if what you reported is still valid?

**Comment by valeriocos** [comment]
I didn't find evidence of this problem, sorry for the late reaction
