### ISSUE TITLE
Better enrichment of Git and GitHub raw indices to calculate metrics for Manuscripts

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-elk#364]
Hey all
I've been trying to calculate the GMD metrics and to add them to Manuscripts.
There are some fields and values that I think should be added to the enriched index when it is being created so that it becomes easier to calculate the metrics related to those fields. The metrics can be derived from some other field in the enriched index, but never the less, I think there is a need to produce better enriched indices for Git and GitHub data sources, for now.
There are several Metrics which need additional data in the enriched indices, and they are as follows:

- [Issue Resolution Efficiency](https://github.com/chaoss/metrics/tree/master/activity-metrics/issue-resolution-efficiency.md). There is an [issue opened under WG-GMD](https://github.com/chaoss/wg-gmd/issues/5) and as you can see from the discussion, we actually need to figure out if issues have a proposed (and accepted PR) for them to be able to get the title of a successfully closed issue.

- [First Response to Issue Duration](https://github.com/chaoss/metrics/tree/master/activity-metrics/first-response-to-issue-duration.md). [Related issue in WG-GMD](https://github.com/chaoss/wg-gmd/issues/8). We may need to calculate the time to first response to the issue.

**NOTE:** I also wanted to put this out there, I think we need to interlink issues and PRs by mentioning the issue number in the proposed PR and vice versa. This way it'll be easier to track down both of them and see the progress.

- [Code Reviews](https://github.com/chaoss/metrics/tree/master/activity-metrics/code-reviews.md): as far as I can tell, there is no information about the reviews that are given to a PR. This information needs to be fetched using the API and added into the enriched index.

- [Code Merge Duration](https://github.com/chaoss/metrics/tree/master/activity-metrics/code-merge-duration.md) | What is the duration of time between code merge request and code commit?

- [Code Review Efficiency](https://github.com/chaoss/metrics/tree/master/activity-metrics/code-review-efficiency.md) | What is the number of merged code changes/number of abandoned code change requests?
- [Maintainer Response to Merge Request Duration](https://github.com/chaoss/metrics/tree/master/activity-metrics/maintainer-response-to-merge-request-duration.md) | What is the duration of time for a maintainer to make a first response to a code merge request?
- [Code Review Iteration](https://github.com/chaoss/metrics/tree/master/activity-metrics/code-review-iteration.md) | What is the number of iterations that occur before a merge request is accepted or declined?
- [Forks](https://github.com/chaoss/metrics/tree/master/activity-metrics/forks.md) | Forks are a concept in distributed version control systems like GitHub. It is a proxy for the approximate number of developers who have taken a shot at building and deploying the codebase *for development*.

- [Pull Request Comment Duration](https://github.com/chaoss/metrics/tree/master/activity-metrics/pull-requests-comment-duration.md) | The difference between the timestamp of the pull request creation date and the most recent comment on the pull request.
- [Pull Request Comment Diversity](https://github.com/chaoss/metrics/tree/master/activity-metrics/pull-requests-comment-diversity.md) | Number of each people discussing each pull request.
- [Pull Request Comments](https://github.com/chaoss/metrics/tree/master/activity-metrics/pull-request-comments.md) | Number of comments on each pull request. 

I think these or fields from which these can be derived need to be added to the enriched indices.

I am also adding issues for the GMD Metrics which need more polishing and definition  under [WG-GMD](https://github.com/chaoss/wg-gmd/issues) repository.
I plan on generating PRs to add the above metrics and this issue can be used as the Parent issue for the same.

**Comment by jgbarah** [comment]
For resolution efficiency, we still need to settle on a definition, @aswanipranjal. Please have a look at my last comment in chaoss/wg-gmd#5. Similar for code review efficiency.

For all metrics on pull requests, I think we can start a new issue. Besides, I know @acs and @valeriocos are planning to work on that, and me too (although I don't know when), we could use that issue to coordinate.

**Comment by aswanipranjal** [comment]
closed by #419.
