### ISSUE TITLE
[github pr raw] Error while inserting raw data for pull_requests category into elasticsearch index

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-elk#396]
I am using `p2o.py` to create a raw index for the `pull_request` data that can be fetched from perceval using the `--category pull_request` flag.

This is the command that I run:-
```
p2o.py --index perceval_github_pr_raw -e http://localhost:9200 --no_inc --debug github --category pull_request -t <token> chaoss grimoirelab-perceval
```

This is the error that is generated:

![screen shot 2018-07-06 at 4 59 03 pm](https://user-images.githubusercontent.com/9946566/42376763-fbdf1520-813d-11e8-9ee3-10d0f9bbb774.png)

AFAIK what is happening is that gelk is unable to insert the `data.review_comments_data.diff_hunk` field into the raw index as it exceeds the max length of 32766.

I am analysing `grimoirelab-perceval` and after a bit of analysis, I see that the PR that is not being added to the raw index is [PR#159](https://github.com/chaoss/grimoirelab-perceval/pull/159).

Apart from that PR, rest all of them are successfully inserted into the raw index

**Comment by valeriocos** [comment]
By default ELK maps all string attributes as keywords to ElasticSearch. However, in some cases ES complains about the size of those attributes (a keyword cannot exceed 32766), thus we have to tune the mappings to avoid this type of errors.
We generally set the mappings for those attributes to text (see 1 below), which allows to search for them through Kibana.  In some cases, when we are not interested in indexing those attributes, we can provide a different mapping (see 2), which makes those attributes not searchable.
 
In the case of GitHub, you should modify the [raw mappings](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/raw/github.py#L40) with either:

1.
```
"properties": {
    "comments_data": {
        "dynamic":false,
        "properties": {
            "body": {
                "type": "text",
                "index": true
            }
        }
    },
    "review_comments_data": {  <----
        "dynamic":false,               
        "properties": {                    
            "body": {                        
                "type": "text",             
                "index": true              
            },                                    
           "diff_hunk": {                    
               "type": "text",               
               "index": true                
           }                                      
        }                                         
    },                         <----
    "body": {
        "type": "text",
        "index": true
    }
}
```
or 2.
```
"properties": {
    "comments_data": {
        "dynamic":false,
        "properties": {
            "body": {
                "type": "text",
                "index": true
            }
        }
    },
    "review_comments_data": {   <----
        "dynamic":false,               
        "properties": {}                                        
    },                          <----
    "body": {
        "type": "text",
        "index": true
    }
}
```

Let me know if this solves your issue

**Comment by aswanipranjal** [comment]
Thank you @valeriocos! That solves it!
