### ISSUE TITLE
Wrong Gitlab url for MR repositories

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#514]
The repository URL is not being correctly handled, so gelk is trying to get a resource that does not exist. For a repository like this: `"https://gitlab.com/Bitergia/devops/sortinghat-utils"` it is trying to get the content from the endpoint `com/api/v4/projects/devops%2F` instead of `com/api/v4/projects/Bitergia%2Fdevops%2F` and we get this beautiful 404 error.
```
Error feeding ocean from gitlab (https://gitlab.com/devops/sortinghat-utils): 404 Client Error: Not Found for url: https://gitlab.com/api/v4/projects/devops%2Fsortinghat-utils/merge_requests?updated_after=1970-01-01T00%3A00%3A00%2B00%3A00&view=simple&sort=asc&state=all&order_by=updated_at&per_page=100
```
This has been seen in the Mordred container version 18.11-01

**Comment by sanacl** [comment]
@valeriocos please read again the description :P

**Comment by valeriocos** [comment]
I don't think the Perceval backend tracks subprojects (https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/gitlab.py#L88). The issue should be reported in perceval, and maybe labeled as enhancement.

**Comment by valeriocos** [comment]
@sanacl , could you try to write the url in the following way:
https://gitlab.com/Bitergia/devops%2Fsortinghat-utils and check if it works for you?

**Comment by valeriocos** [comment]
I have tried to add to the projects.json the project you mention in the following way and no errors popped up:
`https://gitlab.com/Bitergia/devops%2Fsortinghat-utils`

@sanacl, I close this issue, feel free to reopen it.
