### ISSUE TITLE
502 bad gateway with p2o.py

### ISSUE THREAD

**Issue by GregSutcliffe** [chaoss/grimoirelab-elk#522]
I'm trying to use p2o to index a large repo (ansible/ansible, which is ~50k PRs) and it's barely even getting started. I've verified that Elastic is running, and that I can load data into it for a small repo. When I use this command:

(chaoss) root@stats:/opt# p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug github -t mytoken --category pull_request --sleep-for-rate ansible ansible

Then p2o starts up, looks like it's working for a few mins, and then crashes with a 502 error:

```
2018-11-19 10:05:40,821 Error feeding ocean from github (https://github.com/ansible/ansible): 502 Server Error: Bad Gateway for url: https://api.github.com/repositories/3638964/issues?since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&state=all&direction=asc&sort=updated&page=2&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&state=all&direction=asc&sort=updated
Traceback (most recent call last):
  File "/opt/chaoss/lib/python3.5/site-packages/grimoire_elk/elk.py", line 205, in feed_backend
    ocean_backend.feed(category=category)
  File "/opt/chaoss/lib/python3.5/site-packages/grimoire_elk/raw/elastic.py", line 202, in feed
    self.feed_items(items)
  File "/opt/chaoss/lib/python3.5/site-packages/grimoire_elk/raw/elastic.py", line 211, in feed_items
    for item in items:
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/backend.py", line 127, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/backends/core/github.py", line 244, in __fetch_pull_requests
    for raw_pull in raw_pulls:
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/backends/core/github.py", line 541, in pulls
    for raw_issues in issues_groups:
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/backends/core/github.py", line 684, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/backends/core/github.py", line 650, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/opt/chaoss/lib/python3.5/site-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/opt/chaoss/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.github.com/repositories/3638964/issues?since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&state=all&direction=asc&sort=updated&page=2&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&state=all&direction=asc&sort=updated
2018-11-19 10:05:40,828 Done github 
2018-11-19 10:05:40,830 Backend feed completed
```
This happens reliably (I tried it multiple times on two different VMs on different hosting providers). How can I troubleshoot this?

**Comment by valeriocos** [comment]
Hi @GregSutcliffe , thank you for reporting this issue.

I was able to replicate your error using just Perceval. You can find below the Perceval command;
`perceval github ansible ansible --category issue -t 41705dvf1594b047e... --sleep-for-rate`

500 HTTP errors are related to problems with the upstream servers (in this case GitHub), we have a similar issue with another repo (kubernetes/kubernetes). 3-4 weeks ago we contacted the GitHub support but at the moment they cannot give us an ETA to fix this kind of problem.

I would suggest you to concat the GitHub support and report this issue to them.

**Comment by GregSutcliffe** [comment]
So this is purely a GitHub issue? I was afraid of that. Is there a workaround? Can I drop the `--no_inc` and try to build up the index slowly?

**Comment by valeriocos** [comment]
There is a work-around which works from time to time and allows to retrieve more issues/pull requests. It consists in executing the collection process with different `from-date` values . For instance, the first execution you set the from-date to 2018-01-01, the second execution 2017-01-01 and so on. The solution is not perfect but for ad-hoc analysis may be helpful.

**Comment by GregSutcliffe** [comment]
Thanks, presumably that's without `--no_inc` so that the existing data isn't wiped out? I'll give it a try :)

**Comment by valeriocos** [comment]
if you set the `from-date`, the process is not incremental, but it will always start from that date. The platform does delete the data, but overwrites the one that already exists in ElasticSearch.

Good luck! :)

**Comment by GregSutcliffe** [comment]
Ah, so this is just a way to limit the size of the query? That makes sense...

Once I have an initial data set, how do I keep it updated? I want to set up something in cron to get the latest data to Elastic - do I just use drop `--no_inc` and `--from-date` from the original comamnd, or will that revert to trying to query the whole repo?

**Comment by GregSutcliffe** [comment]
I've kicked it off with a from-date of 2018-01-01 just to test, and that seems to be working. Will let you know if it finishes :)

Where do I report the API issue to GitHub, by the way?

**Comment by valeriocos** [comment]
Yes, with the from date attribute the data retrieved from the GitHub API is smaller.

Ideally (if there were no issue with the GitHub repo) you could use [mordred](https://github.com/chaoss/grimoirelab-sirmordred) (which orchestrates the collection/enrichment/visualization processes with incrementality). In tthe current context, maybe you could set up several cron tasks with different `from-date`. All of them will write to the same index and overwrite the data already present.

When I reported the issue to GitHub, I used the form at https://github.com/contact

**Comment by GregSutcliffe** [comment]
When you say "overwrite" does that mean only overwrite the matching data, or will it drop older data? In other words, if I run `--from-date 2018-01-01` today, and `--from-date 2018-11-01` tomorrow, will the second command remove all data older than 2018-11-01? My goal is to build up the archive over time...

I'll report the issue now, thanks for the link!

**Comment by valeriocos** [comment]
if the index already exist (which should be your case), it will overwrite the matching data
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L111

The method `feed_backend` is called by p2o here: https://github.com/chaoss/grimoirelab-elk/blob/master/utils/p2o.py#L58

you're welcome!

**Comment by GregSutcliffe** [comment]
> if the index already exist (which should be your case), it will overwrite the matching data

Aha, so I can build up the dataset over time, perfect! Thanks for the info. If I get a chance I may see about implementing a `--until-date` option so that we can query older data in windows, would that be useful as a patch?

**Comment by valeriocos** [comment]
Nice idea! We have something similar implemented for Git (https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L78), and the generic backend already supports this feature (https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backend.py#L237)

what you propose sounds useful to me, however it is better to ask @sduenas. 
what do you think @sduenas ?

**Comment by GregSutcliffe** [comment]
Oh, that doesn't sound like it'd be too much work at all then! However now I'm waiting 40 mins for my rate limit to refresh :P

**Comment by sduenas** [comment]
It's a good proposal but I don't have time to implement it. I opened an issue in Perceval to support this feature, though. See it in: https://github.com/chaoss/grimoirelab-perceval/issues/466.

We can follow the discussion there. I'm closing this taks.

**Comment by sduenas** [comment]
Perceval now supports this feature.
