### ISSUE TITLE
Parsing webkit-dev pipermail, all items before Oct. 2007 collapse in one month

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#57]
After running:

```
python3 ./p2o.py --enrich --index mls_webkit_dev -e http://localhost:9200 --no_inc --debug pipermail https://lists.webkit.org/pipermail/webkit-dev/
```

I get posts older than Oct. 9th 2007 set to grimoire_creation_date as Oct. 9th, 2007

Note: Issue moved here as recomendation in [Perceval Issue #72](https://github.com/grimoirelab/perceval/issues/72)

**Comment by acs** [comment]
Debugging it right now. Stay tuned!

**Comment by valeriocos** [comment]
any news about this issue? shall we close it, @acs ?

**Comment by acs** [comment]
Closing it because the issue was closed already in perceval: https://github.com/grimoirelab/perceval/issues/72
