### ISSUE TITLE
[Bugzilla] Time open is not being correctly calculated

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-elk#602]
Field `timeopen_days` should take into account the status of the bug to calculate the time. Currently is calculating the time from bug creation to the moment in which the enriched index is generated:

https://github.com/chaoss/grimoirelab-elk/blob/2e7b2ae6c9aac501cde50c9464d025309c235480/grimoire_elk/enriched/bugzillarest.py#L121-L122
There is a field named `is_open` in the index that could be used together to `resolution` and the corresponding date (that could be `last_change_time`, but maybe we need to dive in the history of the bug to make sure if matches the closing event).

**Comment by sduenas** [comment]
This was already fixed.
