### ISSUE TITLE
[mediawiki] Add `grimoire_creation_date` field

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-elk#622]
[Mediawiki enricher](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/mediawiki.py) is not including the standard `grimoire_creation_date` field.

In other cases this is done by calling `get_grimoire_fields` method:
https://github.com/chaoss/grimoirelab-elk/blob/7aeb4496d2c18a94f18a9d24e2fe1aaa5a3140c9/grimoire_elk/enriched/slack.py#L201

https://github.com/chaoss/grimoirelab-elk/blob/7aeb4496d2c18a94f18a9d24e2fe1aaa5a3140c9/grimoire_elk/enriched/enrich.py#L489

So replicating that for [mediawiki enricher](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/mediawiki.py) should be enough to solve this issue..

We need to add this field so the index is aligned with the rest.

**Comment by valeriocos** [comment]
Fixed with: https://github.com/chaoss/grimoirelab-elk/commit/d010acda7f34fe02bc2e029d6de74790f1c1760f
