### ISSUE TITLE
Add option to fetch from selected branches

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-elk#642]
Currently, we can pass which category of items to be fetched from backends but the option doesn't exist for selection of branches.

@valeriocos Please let me know if I could open a PR for this (as I've worked on the changes locally). Thanks!

**Comment by valeriocos** [comment]
For the moment I would push the changes to your gsoc branch (in case we need to modify other things). Next week we could review the work done with @jgbarah and submit later the PR. What do you think ?

**Comment by inishchith** [comment]
> For the moment I would push the changes to your GSoC branch (in case we need to modify other things). Next week we could review the work done with @jgbarah and submit later the PR. What do you think?

@valeriocos Thanks! For now, I've worked on the required changes. I'll make sure to ping you, in case I need help with something :)
Sure. We can submit the PR later.
