### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by jayvdb** [chaoss/grimoirelab-elk#660]
This package has a dependency on cereslib, which also has a dependency on grimoirelab-elk.

While cross-dependencies are supported by pip, especially wheels, it takes some clever tricks to get that to work with setuptools.

It seems like the cereslib dependency here, added because of https://github.com/chaoss/grimoirelab-elk/pull/228 , should be an optional dependency listed in `extras_require` rather than a hard mandatory dependency in `install_requires`.

Possibly this applies to other mandatory dependencies which add features but are not critical for core functionality.

**Comment by jgbarah** [comment]
Sorry, I had not noticed this issue. I agree with your suggestion. What do you think, @valeriocos @sduenas ?

**Comment by xiao623** [comment]
This package has a dependency on cereslib, which also has a dependency on grimoirelab-elk.

Is the above problem sloved?

**Comment by jjmerchante** [comment]
This problem has been solved, we removed the dependency from cereslib.
