### ISSUE TITLE
Not able to see docs link provided in readme

### ISSUE THREAD

**Issue by manikantanr** [chaoss/grimoirelab-elk#673]
Readme file has a [link](https://grimoirelab.gitbooks.io/tutorial) to tutorial in gitbooks, when trying to access its asking login, logged in with gmail still got 404.

Are docs published publicly?

Tried looking at [this](https://legacy.gitbook.com/@grimoirelab) space and found nothing.

**Comment by alpgarcia** [comment]
I guess this is an outdated link. The right one is probably: https://chaoss.github.io/grimoirelab-tutorial/

**Comment by alpgarcia** [comment]
PR ready to be reviewed at #674

**Comment by valeriocos** [comment]
Thanks @alpgarcia and @manikantanr to report this issue
