### ISSUE TITLE
Improve documentation for Grimoirelab-elk

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#692]
Grimoirelab-elk lacks of documentation, it would be great to offer a basic documentation to help newcomers understand how the software works and how they can use it.

The first output of this task should be a TOC and the final output a markdown document.

**Comment by valeriocos** [comment]
Fixed with:
- https://github.com/chaoss/grimoirelab-elk/commit/46b068dbedd0a8f1660d7fc643093e22617699a8
- https://github.com/chaoss/grimoirelab-elk/commit/5045bf512192e17ad6efa98b63327b4e19f01f7d
