### ISSUE TITLE
remove "dashboard" folder

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab-elk#696]
This suggestion is to remove the dashboard folder.

1. We have Sigils for dashboard collections.
2. The [single dashboard](https://github.com/chaoss/grimoirelab-elk/commits/master/dashboards/KIP.json) has not been updated in 2 years and was committed as "draft" only.

**Comment by vchrombie** [comment]
So, just remove the `dashboard` folder. Any more suggestions?

**Comment by valeriocos** [comment]
Hi @vchrombie , yes I checked and it should be safe to remove it!
