### ISSUE TITLE
Update mappings to avoid using mapping types to support ES 7.x

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#711]
Current ES mappings are inheriting `type` parameter since the ages when GrimoireLab was using ES 5.x. It was noted that [mapping types would be deprecated in ES 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/removal-of-types.html).

Actually, current GrimoireLab deployments doesn't work with ES 6.7+ releases as it is explained in [the schedule for removal of mapping_types](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/removal-of-types.html#_schedule_for_removal_of_mapping_types). This is related with chaoss/grimoirelab-sirmordred#318

And of course with issues caused when trying to run GrimoireLab on latest ODFE releases:
chaoss/grimoirelab-sirmordred#330

My first question would be, what these mappings types are used for?

And second, what would be the best strategy to solve this issue? To remove them? To create an specific branch?

If I've read right the code, most of them are in enriched indexes definition (files in `enriched` folder) and probably in `elastic.py#L304` (`create_mappings` method).

**Comment by valeriocos** [comment]
related to https://github.com/chaoss/grimoirelab/issues/219

**Comment by valeriocos** [comment]
Ideally the best strategy is to keep everything in the same branch. Next week I can have a closer look and see how to push this forward.

**Comment by jsmanrique** [comment]
Thank you @valcos. Once we have something working I'd love testing it

**Comment by valeriocos** [comment]
you're welcome, the data is correctly inserted to ODFE, but the panels are not uploaded. I'll check it during this week.

**Comment by jsmanrique** [comment]
> you're welcome, the data is correctly inserted to ODFE, but the panels are not uploaded. I'll check it during this week.

Well, it would be enough for me to start testing how data ingestion work. I don't need the panels yet. So, let's see of I guess how to build my own docker image or pip package to test it

**Comment by valeriocos** [comment]
If you want to test it, you could run sirmordred using the source code: https://github.com/chaoss/grimoirelab-sirmordred#setting-up-a-pycharm-dev-environment

**Comment by valeriocos** [comment]
Fixed with https://github.com/chaoss/grimoirelab-elk/pull/716
