### ISSUE TITLE
It is impossible to install ELK right now due to redis version conflict

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#726]
Hi.
- This repo requires Redis `>=2.10.0, <=2.10.6`, see [here](https://github.com/chaoss/grimoirelab-elk/blob/master/requirements.txt#L6) and [here](https://github.com/chaoss/grimoirelab-elk/blob/master/setup.py#L85)
- For an unknown reason, it also needs Arthur, maybe due to [this](https://github.com/chaoss/grimoirelab-elk/blob/master/setup.py#L85) and [this](https://github.com/chaoss/grimoirelab-elk/blob/master/setup.py#L75), but I believe that I can use `p2o.py` directly on Perceval's output to send data directly to `ES` without `mordred`, `redis` and `arthur`.
- Now arthur needs `redis==3.0.0` [here](https://github.com/chaoss/grimoirelab-kingarthur/blob/master/setup.py#L89) and [here](https://github.com/chaoss/grimoirelab-kingarthur/blob/master/requirements.txt#L2)

Effect: your stack is incompatible with itself, effect is that I cannot just have `perceval` and `p2o.py` installed in a single docker container without manually patching this.

**Comment by lukaszgryglicki** [comment]
Why ever arthur is required? Isn't arthur optional?

**Comment by valeriocos** [comment]
Sorry for the inconvience @lukaszgryglicki , we will fix the redis dependencies. Note that Arthur is currently not used in GrimoireLab and p2o is not mantained since some years. I would suggest you to have a look at [MicroMordred](https://github.com/chaoss/grimoirelab-sirmordred#micro-mordred)

**Comment by lukaszgryglicki** [comment]
So if I want to do all the steps manually what should I do?
My idea was (for each data source):
- Run `perceval` to get data
- Run `p2o.py` to enrich data and send to ES
- Run `sortinghat` to enrich affiliations.

I want to run everything manually myself, so how can I achieve a task say for a single GitHub repository.
I just want to put its data into ES, using minimal tools and then enrich using sorting hat (assuming I have 100s of thousands affiliations data already present in MariaDB instance), what should I do?

**Comment by lukaszgryglicki** [comment]
Or simpler: I have `perceval` output for many many data sources, I just want to send this data to ES (enrich on the way), I thought `p2o.py` was exactly the right tool to do that, without too much dependencies.

I want to have a docker image with the minimal toolset that is able to collect data (perceval), enrich and send to ES (???) and handle affiliations (sortinghat), all I've managed to do after half day struggle was an image 895Mb in size !! Not really ideal for docker/kubernetes containers...

**Comment by lukaszgryglicki** [comment]
Thanks.

**Comment by valeriocos** [comment]
Fixe with #728

**Comment by lukaszgryglicki** [comment]
Thanks.

**Comment by valeriocos** [comment]
you're welcome @lukaszgryglicki !
