### ISSUE TITLE
[question] is it safe to enrich the same index from multiple processes

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#757]
Hi, I have a question:

Is it safe to enrich the same index pair (raw/enriched) say `my-github-issue-raw` and `my-github-issue` via multiple `p2o.py` calls that write different repos data into the same index, for example:

a) `p2o.py --enrich --index my-github-issue-raw --index-enrich my-github-issue -e $ES_URL github --category issue org repo1 -t [redacted] --sleep-for-rate --no-archive`
b) `p2o.py --enrich --index my-github-issue-raw --index-enrich my-github-issue -e $ES_URL github --category issue org repo2 -t [redacted] --sleep-for-rate --no-archive`
...
n) `p2o.py --enrich --index my-github-issue-raw --index-enrich my-github-issue -e $ES_URL github --category issue org repoN -t [redacted] --sleep-for-rate --no-archive`

Assume that there are N such processes running in parallel, writing data for N repos into one `github-issue-raw`/`github-issue` index pair raw/enriched. That will run again in the next few hours and then again and so on.

Will that work OK with resuming enrichment from where it was left by the previous run (which run few hours ago using N parallel processes), obviously each `p2o.py` process would need to have its own "last enriched" data stored in that single index (per repo or whatever)

Asking because on ES 6.8.1 it always worked OK, meaning that for each such raw/enriched index pairs - documents count for raw and enriched were exactly the same, but for Elastic search 7.5.0 it is usually the same, but quite often different and I have no idea what could be happening :/

Is ElasticSearch 7.x fully supported, maybe this is just a coincidence and such parallel processing is not supported by the grimoire stack, but the error only shows in 7.x for an unknown reason?

cc @valeriocos @sduenas

**Comment by jgbarah** [comment]
We're running GrimoireLab sort of that way you mention in Cauldron.io, now with ES 7.x. Up to now we have detected no errors due to that (but testing has not been exhaustive). We only ensure that the same repo is not being updated by two parallel processes at the same time.

**Comment by lukaszgryglicki** [comment]
I was expecting that, I just wanted to confirm my use case is correct.
So I can run N parallel processes writing to the same 1 index, only making sure each of them is for the different repo?
So grimoire *is* storing "last processed date" per repo for each index, right?
I mean can you explain a bit how `p2o.py` resumes work?
Say I have 1 index, it has N repos data - how resuming works?

How about different data sources?
Say `git`, `jira`, `gerrit` and so on?
For example, for `jenkins` we can also have a list of different endpoins, same with `dockerhub`.
So this is not per "repo" as such, but per endpoint,  right?

Is this generic somehow, so it works across all datasources?

**Comment by lukaszgryglicki** [comment]
Eventually, any possible ideas why `raw` index has, say 1100 records and `enriched` has for example `580`, after subsequent `p2o.py` runs 9and only happens on one ES instance and never on the second ES instance? Any clue? ideas? Was struggling with that 10 hours and starting to run out of ideas ...

**Comment by jgbarah** [comment]
Yes, that's basically the loop. I've tested it works in parallel, as you describe, for git, GitHub, GitLab. Not sure about others. Pretty sure it won't work with Gerrit, because in that case the strategy (due in part to peculiarities in the Gerrit API) is to get *all* code reviews at once, if I'm not wrong. That could also happen with other data sources (maybe Jira). In those cases, I'm not completely sure, but probably you could update the raw index with a single process (for all the repos of a given data source), and then enrich in parallel (but I have not tested that).

For the record, in Cauldron we're not using p2o, but a Python wrapper on top of Mordred.

**Comment by lukaszgryglicki** [comment]
Makes sense, thanks.
We're not using `mordred` because it's too "heavy", we've written our own orchestrator called SDS (sync data sources) and it orchestrates `p2o.py` executions on multiple kubernetes nodes (spawning each in just a single goroutine), using multiple processes on each node (number of `p2o.py` processes on each node is equal to the number of CPU cores reported on that node).
Sources here: https://github.com/LF-Engineering/sync-data-sources, actually deployment using Helm there: https://github.com/LF-Engineering/sync-data-sources/tree/master/helm-charts/sds-helm

**Comment by jgbarah** [comment]
Thanks for the pointers!

**Comment by lukaszgryglicki** [comment]
Probably the cause for this is here:  https://github.com/chaoss/grimoirelab-elk/issues/758
