### ISSUE TITLE
[Bug?] ES 7.X exceeding maximum scrolls [500] is ignored. ELK tools should remove scroll when they no more need it.

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#758]
So when I run a big batch of `p2o.py` commands (about 1900) using about 32 in parallel (running on 2 kubernetes nodes each having 16 CPU cores, so 32 `p2o.py` processes at the same time) I'm hitting ES 7.X error "too many scrolls open".

The funny part is that I would never detect that because `p2o.py` runs "as usual" reporting no failure and even no warning, the result is that no new data comes into the enriched index.

This runs OK on ES 6.X probably because the number of allowed scrolls is bigger (both 6.X and 7.X) initially have no setting to be checked by `curl (...)/_cluster/settings?pretty" | grep max_open_scroll`. You can set that value via specific `curl -XPUT (...)/_cluster/settings` call. My guess is that 6.x has no limit for that value or the limit is much higher than 500 (I was monitoring this value via `curl (...)/_nodes/stats/indices/search?pretty | grep "open_contexts"` while sync was running and 6.X allowed much over 1000 while 7.X go to 500 and stopped.

I've detected this just by pure luck, my other script was trying to save entire index data (one index) into JSON file using scroll API and it failed with
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "exception",
        "reason" : "Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting."
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "sds-hyperledger-fabric-github-issue",
        "node" : "p_8cDIekSPWjJ4mEitZ2KA",
        "reason" : {
          "type" : "exception",
          "reason" : "Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting."
        }
      }
    ]
  },
  "status" : 500
}
```

So I've run one of `p2o.py` commands manually while. 7.X was on the 500 scrolls limit and it just finished OK, without any warning or error.

==========================

So the problem is:

1) why `p2o.py` creates more than 32 scrolls when only 32 `p2o.py` instances are run in parallel, no more? My guess is that grimoire-elk library (which is used by `p2o.py`) is *NOT* clearing index after it no more uses it, see:
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elastic_items.py#L201-L205

The scroll is set to even 10 minutes there (according to comment) but I don't see scroll released after no more used. ElasticSearch API docs strongly suggest that scrolls should be removed after they're no more needed, see: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#_clear_scroll_api

My guess is that having > 1000 scrolls are just leftovers from finished `p2o.py` calls. I think each call should clean up its scroll, like for example here: https://github.com/LF-Engineering/darst/blob/master/utils/get_all_index_docs.sh#L69-L70

2) I think `p2o.py` and other stuff using https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elastic_items.py file should check if scrolls are available and if not it should return an error or at least a warning. The other option is to wait for some scroll(s) to become available. But the most important is to FREE the one that was used in the current instance and is no more needed!

I think (not yet 100% sure) that this is the real cause of https://github.com/chaoss/grimoirelab-elk/issues/757

cc @sduenas @valeriocos

**Comment by lukaszgryglicki** [comment]
Ping... 
cc @jgbarah

**Comment by svdo** [comment]
Do you think #760 might be related?

**Comment by jgbarah** [comment]
> Ping...

Sorry for being silent. We have that in our plate, we agree with your diagnosis. i think the most urgent action is to release the scroll when it is no longer used, in GrimoireELK, as you mention. If you have some time, could you produce a pr with that?

In any case, i agree that likely we should also check if there was a scroll error, and (likely) schedule a retry some minutes later, when hopefully a new scroll is available.

**Comment by jgbarah** [comment]
> Do you think #760 might be related?

Mmmm. I don't think so, symptoms seem different... But I don't have a lot of experience with Graal... Are you using Elasticsearch 7.x too? (I think the container you mention has ES 6.x in it...)

**Comment by svdo** [comment]
@jgbarah You're probably right:

```
grimoire_elk.elastic - DEBUG - Found version of ES instance at http://localhost:9200: 6.
```

**Comment by lukaszgryglicki** [comment]
I can try to create a PR, but need to work on some other more urgent stuff right now. I will comment here when I'm free to work on this, so before I post any comment, somebody else can start work on it but please also comment here, so I won't duplicate anybody else's work.

**Comment by jgbarah** [comment]
OK, @lukaszgryglicki, thanks!

**Comment by lukaszgryglicki** [comment]
Unless no one else works on this I'll take it in 12-13 hours since then.

**Comment by lukaszgryglicki** [comment]
Starting to work on this.

**Comment by lukaszgryglicki** [comment]
Created a PR that:
- Releases scroll after finished using it
- Wait a configurable amount of time (default 900s) when no scroll is available
