### ISSUE TITLE
[cocom] [colic] Dashboards display tokens in URLs

### ISSUE THREAD

**Issue by svdo** [chaoss/grimoirelab-elk#759]
This is the same issue as was fixed by #682, but now for the Code Complexity and the Code Licenses dashboards. Both the "Repositories" and the "All Files: Code complexity, LOC and ratios" panels on the Code Complexity dashboard, as well as the "Repositories" and "All Files: License & Copyright Definition" panels on the Code Licenses dashboard display username and token in the URLs.

**Comment by valeriocos** [comment]
Fixed with #763 and chaoss/grimoirelab-sigils#414
