### ISSUE TITLE
ELK resuming data collection support for different data sources

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#762]
Hi, is it possible to get a list of data source types and their support to resume data collection?
By resume data collection I mean I'm running `p2o.py` for the first time, so all data is collected and enriched. Then (say the next day) I'm running that `p2o.py` again against the same ElasticSearch instance, so the index is there and collecting data only requires processing data since yesterday.
Which data sources will just collect data from yesterday to now, so the resume mode is supported? Which data sources will collect all data again, so in practice we will have data from the beginning till yesterday duplicated?
We're experiencing issues with some data-sources data being fetched and stored multiple times...
So how about resume support in those data sources:
```
    bugzilla         Fetch bugs from a Bugzilla server
    bugzillarest     Fetch bugs from a Bugzilla server (>=5.0) using its REST API
    confluence       Fetch contents from a Confluence server
    discourse        Fetch posts from Discourse site
    dockerhub        Fetch repository data from Docker Hub site
    gerrit           Fetch reviews from a Gerrit server
    git              Fetch commits from Git
    github           Fetch issues, pull requests and repository information from GitHub
    gitlab           Fetch issues, merge requests from GitLab
    groupsio         Fetch messages from Groups.io
    jenkins          Fetch builds from a Jenkins server
    jira             Fetch issues from JIRA issue tracker
    mbox             Fetch messages from MBox files
    meetup           Fetch events from a Meetup group
    pipermail        Fetch messages from a Pipermail archiver
    slack            Fetch messages from a Slack channel
```
?
We're calling every `p2o.py` sync like this - maybe something is wrong there?
`p2o.py --enrich --index sds-yocto-groupsio-raw --index-enrich sds-yocto-groupsio -e [[redacted_but_always_the_same]] --db-host mariadb.mariadb --db-sortinghat sortinghat --db-user sortinghat --db-password [[pwd]] groupsio yocto+yocto-bsp -e [[email]] -p [[pwd]] --no-verify`

**Comment by jgbarah** [comment]
AFAIK, all data sources which are not point-retrieved can be updated incrementally, assuming the first retrieval completed. Some of the data sources (notably Gerrit, but may be others) don't provide items in order, which means that until you have a complete batch (say, the first complete retrieval of the data source) you cannot start incrementally.

By "point-retrieved", y mean those data sources which are providing not the whole history of what happened (like for example GitHub, where you have all the issues, be them open or closed, etc.), but only a snapshot (like for example DockerHub, where the API provides only the current numbers).

Is this what you were needing?

**Comment by sduenas** [comment]
There's no such list but you cat get check the backends that support resuming doing this:

```
from perceval.backend import find_backends
import perceval.backends

backends = sorted([   
    name for name, backend in find_backends(perceval.backends)[0].items()
    if backend.has_resuming()
])

print(backends)

['askbot',
 'bugzilla',
 'bugzillarest',
 'confluence',
 'discourse',
 'dockerhub',
 'git',
 'github',
 'gitlab',
 'googlehits',
 'groupsio',
 'hyperkitty',
 'jira',
 'kitsune',
 'launchpad',
 'mbox',
 'meetup',
 'nntp',
 'phabricator',
 'pipermail',
 'redmine',
 'remo',
 'stackexchange',
 'supybot',
 'telegram']

```

**Comment by valeriocos** [comment]
@lukaszgryglicki can we close this issue? thanks

**Comment by lukaszgryglicki** [comment]
Yes, I think we can.
