### ISSUE TITLE
Imports perceval.mozilla backends, which don't seem to exist in the perceval repository?

### ISSUE THREAD

**Issue by stuartlangridge** [chaoss/grimoirelab-elk#80]
Running `p2o.py` from a git checkout is looking for `perceval.backends.mozilla`:

    Traceback (most recent call last):
      File "./GrimoireELK/utils/p2o.py", line 31, in <module>
        from grimoire_elk.arthur import feed_backend, enrich_backend
      File "/home/aquarius/Work/LQ/PercevalBackends/GrimoireELK/utils/grimoire_elk/arthur.py", line 35, in <module>
        from .utils import get_elastic
      File "/home/aquarius/Work/LQ/PercevalBackends/GrimoireELK/utils/grimoire_elk/utils.py", line 116, in <module>
        from perceval.backends.mozilla.kitsune import Kitsune, KitsuneCommand
    ImportError: No module named 'perceval.backends.mozilla'

but as far as I can tell, the perceval repository at https://github.com/grimoirelab/perceval/tree/master/perceval/backends doesn't have such a thing at all; there's `perceval.backends.core`, but no `perceval.backends.mozilla`. Do I have some sort of version mismatch?

**Comment by herotest** [comment]
try installing  perceval-mozilla
pip3 install perceval-mozilla

**Comment by smitthakkar96** [comment]
any update on this, I am trying to set it up on my end but I am running into issues

**Comment by smitthakkar96** [comment]
Actually after a work around I was able to set the things up and I realized that the things were not upto date so I cloned perceval, grimoirelab-toolkit and perceval-mozilla from git and ran setup manually and it ran.

**Comment by ghasabian** [comment]
$ git clone https://github.com/grimoirelab/perceval-mozilla.git
$ pip3 install -r requirements.txt
$ python3 setup.py install

it fixes the problem
