### ISSUE TITLE
Update schemas to latest format

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-elk#803]
ELK keeps a description for each enriched data used to build the KIbiter dashboards. Such descriptions are stored in the folder [schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema) as CSV files. Over time, these descriptions have evolved and the current format is defined as a list of attributes that include the name, the type, whether the field can be aggregated and a description (e.g., https://github.com/chaoss/grimoirelab-elk/blob/master/schema/git.csv). Nevertheless, some schemas are still not aligned with the latest format. For instance, this is the case for:
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/stackoverflow.csv
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/dockerhub.csv
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/meetup.csv
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/bugzilla.csv
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/askbot.csv

The goal of this issue is to update the schemas to the latest format. In order to do so, given a data source (e.g., meetup, stackoverflow), micro-mordred[*]  should be executed to collect and enrich the data. Then, the enriched documents should be inspected using the dev tools or the discover of Kibiter. For each attribute found in the enriched index, the corresponding schema should contain the name of the attribute, the type, whether the field can be aggregated and a description.

Note that some fields like the `grimoire_creation_date`, `project`, `project_1`, `origin`, etc. are shared across all enriched indexes and their descriptions can be taken from existing schemas.

[*] Details to execute micro-mordred for a given data source are available at: https://github.com/chaoss/grimoirelab-sirmordred#supported-data-sources

**Comment by vchrombie** [comment]
Hi @valeriocos 
I was trying to work on this issue.

I started with the askbot. In the process, I faced a few issues. I think there is a mistake in the [askbot configurations](https://github.com/chaoss/grimoirelab-sirmordred#askbot). 

I think there is a typo with `askbot_enrcihed` in the setup.cfg 
Also, it seems that https://ask.puppet.com/ is no longer active. I searched for some more askbot sites, and I got this https://ask.sagemath.org/questions/. Is it required to change it?

**Comment by vchrombie** [comment]
Hi @valeriocos 

> I think there is a typo with `askbot_enrcihed` in the setup.cfg
> Also, it seems that https://ask.puppet.com/ is no longer active. I searched for some more askbot sites, and I got this https://ask.sagemath.org/questions/. Is it required to change it?

I changed it and I could be able to run the script, but unusually it is taking really long time. I will try to see what could be the issue and update you about it.

**Comment by valeriocos** [comment]
Sorry for the late reply @vchrombie , I thought I had answered this message

> I started with the askbot. In the process, I faced a few issues. I think there is a mistake in the askbot configurations.

>I think there is a typo with askbot_enrcihed in the setup.cfg
Also, it seems that https://ask.puppet.com/ is no longer active. I searched for some more askbot sites, and I got this https://ask.sagemath.org/questions/. Is it required to change it?

Please fix the mistake. WRT the askbot server, there is no specific site to target. You can try with https://askbot.org (in the past we were mining it, I have just tried with perceval* and it seems to work fine)

[*] perceval askbot https://askbot.org --no-archive

**Comment by vchrombie** [comment]
> Sorry for the late reply @vchrombie , I thought I had answered this message

No problem. :slightly_smiling_face: 

> Please fix the mistake. 

Sure, I will do it by night.

> WRT the askbot server, there is no specific site to target. You can try with https://askbot.org (in the past we were mining it, I have just tried with perceval* and it seems to work fine)
> 
> [*] perceval askbot https://askbot.org --no-archive

Oh okay, I will try and get back to you.

> Yes, sorry the URL should be the main one (`questions` is added automatically here: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/askbot.py#L268)

Thanks for the reply @valeriocos.

**Comment by vchrombie** [comment]
Hi @valeriocos 
Thanks for your earlier reply. It solved a few issues.

Just a quick update. I have executed the micro-mordred for the askbot backend.

![image](https://user-images.githubusercontent.com/25265451/77196120-bfccc580-6b08-11ea-9dbb-1089131fc90b.png)

It is taking so much time, but ya fine with it. After some time, the index was created and I could inspect the index using the kibiter.

I tried this `GET /askbot/_mapping` in the dev tools and I got the fields along with the mappings. The total number was 51.
I checked the index in the Management >> Kibana >> Index Patterns and it has 56 fields. I assume we need to ignore the first 5 fields. Correct me if I am wrong?

![image](https://user-images.githubusercontent.com/25265451/77201583-bc3e3c00-6b12-11ea-9104-b8d0f82bd199.png)

This gist has the 51 fields, [askbot_schema gist](https://gist.github.com/vchrombie/69ddf7a0b6affc7ec7c5f8702dc67ea9#file-askbot_schema). 

Can you have a look at it and tell if I am correct till this point? I will collect the descriptions and other things before sending a PR.

**Comment by vchrombie** [comment]
Hi @valeriocos 

When I was working on the askbot schema, I faced a small issue during the enrichment face. Here is the log, [askbot-log](https://gist.github.com/vchrombie/44d60738a2c75b35d524bb7c93371537).

```
  2020-03-21 00:48:59,531 Error enriching raw from askbot (https://askbot.org/): 'username'
Traceback (most recent call last):
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/elk.py", line 533, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/elk.py", line 321, in enrich_items
    total = enrich_backend.enrich_items(ocean_backend)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/enriched/askbot.py", line 329, in enrich_items
    (answers, comments) = self.get_rich_item_answers_comments(item)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/enriched/askbot.py", line 307, in get_rich_item_answers_comments
    eanswer = self.get_rich_answer(item, answer)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/enriched/askbot.py", line 267, in get_rich_answer
    eanswer['author_askbot_user_name'] = answer['answered_by']['username']
KeyError: 'username'
```

There was no trouble with the enrichment. I didn't understand what could the problem. I thought of asking it here.

**Comment by valeriocos** [comment]
Hi @vchrombie,

This kind of issues is generally related to a user that removed his account. In this case, the enricher is assuming that the username is always there. A possible to solution is to use the get method as follows: `answer['answered_by'].get('username')`. However, this may require to patch other parts of the code.

Waiting for a patch to fix this bug :)

**Comment by vchrombie** [comment]
Hi @valeriocos.
 
> This kind of issues is generally related to a user that removed his account. In this case, the enricher is assuming that the username is always there. A possible to solution is to use the get method as follows: `answer['answered_by'].get('username')`. 

Thanks for the clarification.

> However, this may require to patch other parts of the code.

Other parts you mean, in elk.py or just askbot.py? 

> Waiting for a patch to fix this bug :)

Can I work on this, if you don't have any problem?

**Comment by valeriocos** [comment]
> Thanks for the clarification.

You're welcome!

> Other parts you mean, in elk.py or just askbot.py?

Just askbot.py

> Can I work on this, if you don't have any problem?

Sure, please start when you have time

Thanks!

**Comment by vchrombie** [comment]
> https://github.com/chaoss/grimoirelab-elk/issues/803#issue-580129473

The updated list is

- [ ] https://github.com/chaoss/grimoirelab-elk/blob/master/schema/stackoverflow.csv
- [x] https://github.com/chaoss/grimoirelab-elk/blob/master/schema/dockerhub.csv
- [ ] https://github.com/chaoss/grimoirelab-elk/blob/master/schema/meetup.csv
- [ ] https://github.com/chaoss/grimoirelab-elk/blob/master/schema/bugzilla.csv
- [x] https://github.com/chaoss/grimoirelab-elk/blob/master/schema/askbot.csv

**Comment by rohanreddych** [comment]
Hello! I started working on `stackoverflow.csv` for getting the description and aggregatable, I tried to run griomoirelab locally using docker. This is the output
```
Starting container: 98c45c639e0f
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -                   
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld.
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -                   
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
..Kibiter started
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Collection for git: starting...
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
53/53 unique identities loaded
Collection for git: finished after 00:01:01 hours
Collection for git: starting...
Collection for git: finished after 00:00:00 hours
Collection for git: starting...
Collection for git: finished after 00:00:00 hours
```
I uncommented stackoverflow from `setup.cfg` added an API key. modified `projects.json` to 
```
{
    "Chaoss": {
        "stackexchange": [
            "http://stackoverflow.com/questions/tagged/chef",
            "http://stackoverflow.com/questions/tagged/chefcookbook",
            "http://stackoverflow.com/questions/tagged/ohai",
            "http://stackoverflow.com/questions/tagged/test-kitchen",
            "http://stackoverflow.com/questions/tagged/knife"
        ]
    },
    "grimoirelab": {
      "meta": {
        "title": "GrimoireLab"
      },
      "git": [
          "https://github.com/chaoss/grimoirelab.git"
        ]
    }
  }
```

But stackoverflow data is not being collected and shown. Only git and github data is being shown. 

![Screenshot from 2021-03-22 18-19-55](https://user-images.githubusercontent.com/43641071/111992387-5f1d0200-8b3b-11eb-8ad7-1f7bae89d941.png)

So, I tried using https://chaoss.biterg.io. In https://chaoss.biterg.io/app/kibana#/management/kibana/indices/stackoverflow?_g=()&_a=(tab:indexedFields) there is no field called `answer_status` which is the first field in https://github.com/chaoss/grimoirelab-elk/blob/master/schema/stackoverflow.csv .

I appreciate any help on what i am doing wrong

**Comment by vchrombie** [comment]
Hi @rohanreddych 

> I tried to run griomoirelab locally using docker

The docker image is quite outdated and hasn't been updated so long. It might not have the latest changes to that enriched. It would be great if you can try the [docker-compose](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) method. This is almost similar to the docker method except this uses the latest releases. It would be even great if you are using the developer setup for GrimoireLab.

> But stackoverflow data is not being collected and shown. Only git and github data is being shown.

One reason could be the time. It looks like there are many sources, so it might take 10-15 minutes for the data to appear on the dashboards. Else it could be an issue of the outdated image or some typo in the configurations.

> there is no field called answer_status which is the first field in https://github.com/chaoss/grimoirelab-elk/blob/master/schema/stackoverflow.csv

The fields might be deprecated now, so the schema should be updated as well.

**Comment by vchrombie** [comment]
For the people who are interested to work on this issue.

You can execute [micro-mordred](https://github.com/chaoss/grimoirelab-sirmordred#micro-mordred-) to collect and enrich the data of a particular data source. You can inspect the enriched documents using the dev tools or the discover of Kibiter. For each attribute found in the enriched index, the corresponding schema should contain the name of the attribute, the type, whether the field can be aggregated, and a description.
[More Information](https://github.com/chaoss/grimoirelab-elk/issues/803#issue-580129473).

You can use this script for automating the process and creating the schema file from the index.
https://gist.github.com/vchrombie/bf6a682edcf47624126317897e58679c

**Comment by rohanreddych** [comment]
I used docker-compose as @vchrombie suggested, it worked. Can you please review the pull request?
Thanks for the help. 😀

**Comment by vchrombie** [comment]
Closing this issue in favour of https://github.com/chaoss/grimoirelab-elk/issues/1010
