### ISSUE TITLE
[gitter] Adding data storage for gitter

### ISSUE THREAD

**Issue by imnitishng** [chaoss/grimoirelab-elk#820]
Since a new backend `gitter`  https://github.com/chaoss/grimoirelab-perceval/pull/632 has been added to perceval backend I was wondering if we can store the raw data in Elasticsearch and proceed forward to the implementation of this backend in `sir-mordred`?
I can start working on this. Please inform me if there some complications I'm missing.
WDYT @valeriocos?

**Comment by valeriocos** [comment]
Hi @imnitishng , that's a good idea!

Please start when you have time. As a reference, have a look at the raw and enrich connectors of mattermost (I guess they will be simiar to the ones for Gitter):
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/raw/mattermost.py
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/mattermost.py

Thanks!

**Comment by imnitishng** [comment]
Sure I will start the work and send a PR ASAP. Thanks.
