### ISSUE TITLE
[Pagure] Implement Pagure backend to GrimoireLab ELK

### ISSUE THREAD

**Issue by animeshk08** [chaoss/grimoirelab-elk#821]
A new backend [Pagure](https://github.com/chaoss/grimoirelab-perceval/pull/621) has been added to Perceval. Implement the backend to store the indexes in GrimoireLab ELK

**Comment by animeshk08** [comment]
Sorry for the delay with this work. I was still yet to be comfortable with the working of ELK and was also lagging a bit in the micro-tasks, I will submit a PR for this soon.

**Comment by valeriocos** [comment]
Hi @animeshk08 , no worries! Feel free to start when you have time, thanks!
