### ISSUE TITLE
Anonymize user information coming from Perceval

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab-elk#822]
We need a way to anonymize the personal information that comes from Perceval. Names, emails and information that may be related to the users of each backend must be hidden.

The information stored in the Elasticsearch indexes should only be identifiers that cannot be related directly with the user.

I will open a pull request for Git, GitHub, Gitlab and Meetup that are the current data sources of Cauldron.

**Comment by valeriocos** [comment]
Fixed with #824
