### ISSUE TITLE
Make sure that all indexes are deleted when a test is finished

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-elk#837]
When executing the test suite, only the raw and enriched indexes are deleted, see https://github.com/chaoss/grimoirelab-elk/blob/master/tests/base.py#L145.

A possible solution is to change the logic at https://github.com/chaoss/grimoirelab-elk/blob/master/tests/base.py#L145 to delete all indexes or use wildcards (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html).

**Comment by valeriocos** [comment]
@imnitishng let me know if you want to work on this issue, thanks!

**Comment by imnitishng** [comment]
Yes sure @valeriocos. I'll start the work ASAP!

**Comment by valeriocos** [comment]
Thank you @imnitishng !
