### ISSUE TITLE
Evaluate how to increase test coverge for enriched/mbox_study_kip.py

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-elk#840]
The test coverage of https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/mbox_study_kip.py is extremely low.  This is probably due to the fact that the [test data](https://github.com/chaoss/grimoirelab-elk/blob/master/tests/data/mbox.json) for mbox doesn't contain information to trigger this study (ref [here](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/mbox_study_kip.py#L87)), which is tested at https://github.com/chaoss/grimoirelab-elk/blob/master/tests/test_mbox.py#L159.

The goal of this issue is to evaluate why the coverage is low and include more test data for mbox if needed.

**Comment by valeriocos** [comment]
@imnitishng let me know if you are interested in taking this issue (it isn't urgent), thanks!

**Comment by imnitishng** [comment]
Hi @valeriocos, I'd love to work on this. As soon as I complete some work on other PRs I will start the work here. Thanks.

**Comment by valeriocos** [comment]
Great, thank you for helping @imnitishng !
