### ISSUE TITLE
Unable to load the generated dashboards

### ISSUE THREAD

**Issue by smitthakkar96** [chaoss/grimoirelab-elk#86]
![screen shot 2017-06-28 at 12 54 52 pm](https://user-images.githubusercontent.com/10204970/27672336-c617007a-5cb7-11e7-8490-7054d1e215da.png)

**Comment by smitthakkar96** [comment]
I am using ES and kibana 5.4.2

**Comment by valeriocos** [comment]
Extremely late reply (sorry about that @smitthakkar96). Currently, we use ES 6.1.0 and KIbana 6.1.4-2, you can find a docker-compose at: https://github.com/chaoss/grimoirelab-sirmordred#source-code-and-docker. Please open a new issue, if you experience the same problem.

Thanks!
