### ISSUE TITLE
Jenkins data collected by p2o.py seems to be incomplete

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#875]
Hi, when I run:
-  `p2o.py --enrich --index jenkins-raw --jenkins -e [redacted] -g --db-host ... --db-sortinghat ... --db-user ... --db-password ... jenkins https://jenkins.opendaylight.org/releng/ --no-archive`
it seems like some data is not collected.
Log includes:
```
2020-05-13 12:55:53,483 [jenkins] Problems parsing job name infrautils-sonar
2020-05-13 12:55:53,483 list index out of range
2020-05-13 12:55:53,486 [jenkins] Problems parsing job name jsonrpc-sonar
2020-05-13 12:55:53,486 list index out of range
2020-05-13 12:55:53,487 [jenkins] Problems parsing job name jsonrpc-sonar
2020-05-13 12:55:53,487 list index out of range
2020-05-13 12:55:53,491 [jenkins] Problems parsing job name lispflowmapping-sonar
2020-05-13 12:55:53,491 list index out of range
2020-05-13 12:55:53,522 [jenkins] Problems parsing job name openflowplugin-sonar
```
What does it mean? How can I fix this?

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki,

The problem occurs in this block https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/jenkins.py#L144-L164 and it is due to the fact that some jobs don't follow the schema defined in that code. 

We can improve the code to be aligned with the schema followed by the jobs in https://jenkins.opendaylight.org/releng/

**Comment by lukaszgryglicki** [comment]
Would be great to have that! THANKS!

**Comment by valeriocos** [comment]
Perfect, you're welcome! How do you want to proceed?

Please note that the problem doesn't affect the working of the enricher, just that the information collect from [get_fields_from_job_name](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/jenkins.py#L236) won't be inserted in the enriched items.

**Comment by lukaszgryglicki** [comment]
So there will be no changes in enriched ES index right? If so then we don't need to change anything. We're not using raw indices for anything.

**Comment by valeriocos** [comment]
> So there will be no changes in enriched ES index right?

The enriched index will include values for the fields below.
```
extra_fields = {
            'category': None,
            'installer': None,
            'scenario': None,
            'testproject': None,
            'pod': None,
            'loop': None,
            'branch': None
        }
```
In your case when you see the log message `[jenkins] Problems parsing job name...`, these fields are empty

**Comment by valeriocos** [comment]
@lukaszgryglicki please let me know if we can close this issue or there is some action to take, thanks

**Comment by lukaszgryglicki** [comment]
I'll ask my team.

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki let's close this issue, feel free to reopen it if needed.
