### ISSUE TITLE
[Rocket.Chat] Add rocketchat backend support to ELK 

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-elk#876]
This issue in reference to the PR, https://github.com/chaoss/grimoirelab-perceval/pull/661.

It is about adding rocketchat backend support to grimoirelab-elk.

@animeshk08, I want to know if you are working on this. If not, I would like to take this up this, and would you be interested to review? As you have some pretty good experience with elk already, it would be great if you can help me by reviewing the work.

**Comment by animeshk08** [comment]
Hi, @vchrombie. Sorry, but I have already created the enricher for this backend. I just to finalize the unit tests and I will be creating a PR either today or tomorrow :)

**Comment by vchrombie** [comment]
> Hi, @vchrombie. Sorry, but I have already created the enricher for this backend. I just to finalize the unit tests and I will be creating a PR either today or tomorrow :)

No problem, you can complete the PR. You can reference this issue so that it would close after the PR is merged.

**Comment by vchrombie** [comment]
I think this can be closed with the recent merge #890.

**Comment by valeriocos** [comment]
Yes, thanks @vchrombie . Feel free to close it
