### ISSUE TITLE
[cocom] the hash of the repository url does not always the same value

### ISSUE THREAD

**Issue by florentk** [chaoss/grimoirelab-elk#899]
https://github.com/chaoss/grimoirelab-elk/blob/a5140cb95d665efeb86ee569e8a3530319d7b3b9/grimoire_elk/enriched/cocom.py#L360

`hash()` method return the hash of the object (not the hash of the string). Then, probably depending on the environment, the hash of the repository url is not already the same, resulting in duplicate entry.

You can see that [here](https://metrics.kiwix.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(total_loc,_id,repo_url,origin),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b9310c20-1849-11ea-8930-836c4cc0aa6f,key:_index,negate:!f,params:(query:cocom_chaoss_study,type:phrase),type:phrase,value:cocom_chaoss_study),query:(match:(_index:(query:cocom_chaoss_study,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b9310c20-1849-11ea-8930-836c4cc0aa6f,key:language,negate:!f,params:(query:Shell,type:phrase),type:phrase,value:Shell),query:(match:(language:(query:Shell,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b9310c20-1849-11ea-8930-836c4cc0aa6f,key:repo_url,negate:!f,params:(query:'https:%2F%2Fgithub.com%2Fkiwix%2Fmaintenance',type:phrase),type:phrase,value:'https:%2F%2Fgithub.com%2Fkiwix%2Fmaintenance'),query:(match:(repo_url:(query:'https:%2F%2Fgithub.com%2Fkiwix%2Fmaintenance',type:phrase))))),index:b9310c20-1849-11ea-8930-836c4cc0aa6f,interval:auto,query:(language:lucene,query:''),sort:!(grimoire_creation_date,desc)))

We recommand to use hashlib : 

`hashlib.md5(repository_url_anonymized).hexdigest()`

related with https://github.com/kiwix/metrics/issues/60

**Comment by kelson42** [comment]
Could this bug be confirmed?
