### ISSUE TITLE
[Maniphest] Wrong data in fields time_open_days_enrich and timeopen_days.

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-elk#910]
Using the current version deployed in one of the biterg.io instances I've seen that the field with the "time opened" is not correct at all. Instead of calculating the time from creation to resolution, it is offering something else, my bet is it is offering time from creation to last modification.

![image](https://user-images.githubusercontent.com/326719/86825004-2d3c3c00-c08f-11ea-99c6-477f0f7331f1.png)

The image above shows the data we have for a ticket created on March 18th and closed on March 19th.

![image](https://user-images.githubusercontent.com/326719/86825124-4d6bfb00-c08f-11ea-86f1-dfc0024b6117.png)

I think it is not a coincidence that the number of days since it was create until today is **111**

How to reproduce:
* go to a dashboard with Maniphest
* add a tag in any of the closed tickets
* see the time open for this ticket on the dashboard. Fields `time_open_days_enrich` or ` timeopen_days` (I guess they contain the same info)

**Comment by zhquan** [comment]
The value `time_open_days_enrich` is calculated as the diff between `creation_date` and now
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/phabricator.py#L314

And the field `timeopen_days` has the same value as `time_open_days_enrich` https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/phabricator.py#L366

Maybe we should do something like in Gerrit https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/gerrit.py#L251 

```
if eitem['status'] in ['Open]:
    eitem['time_open_days_enrich'] = get_time_diff_days(eitem['creation_date'],
                                                        datetime_utcnow().replace(tzinfo=None))
else:
    eitem['time_open_days_enrich'] = get_time_diff_days(eitem['creation_date'],
                                                        eitem['modification_date'])
```
And create a scripted field (`painless_delay`) to calculate the real `timeopen_days` when the task is still open as
```
if (doc.containsKey('status') && doc['status'].value != 'Open') {
  return doc['time_open_days_enrich'].value;
} else {
  return Duration.between(LocalDateTime.ofInstant(Instant.ofEpochMilli(doc['grimoire_creation_date'].value.millis), ZoneId.of('Z')), LocalDateTime.ofInstant(Instant.ofEpochMilli(new Date().getTime()), ZoneId.of('Z'))).toMinutes()/1440.0;
}
```
WDYT @sanacl

**Comment by sanacl** [comment]
Hey @zhquan 

the issue I see is not whether the time is more or less accurate when it is open, the issue I see is the `time_open_days_enrich` does not show the time from creation_date until status changed to any closed status (resolved, won't fix, etc ..)

What you suggest does not solve this issue as far as I understand.

**Comment by zhquan** [comment]
Hi @sanacl,

I realize that in the image you are using `time_to_close_days` but all your comments are related to `time_open_days_enrich`.

- `time_to_close_days`: Is calculated between `creation_date` and `updated_date` (https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/phabricator.py#L309). In your image, the task was closed on March 19th but the last update was on July 7th. So this field `time_to_close_days` will calculate with July 7th.

**Comment by sanacl** [comment]
I did not know about `time_to_close_days`. I may use it :) 

The thing about `time_open_days_enrich` is that it is not calculated as the diff between `creation_date` and now, it is calculated between `creation_date` and the latest change enriched. So if a ticket was open on January 1st and the last change (a tag was added) was done in January 2nd, the value for `time_open_days_enrich` will be **1**.

Then, the question that come up to my mind is, shouldn't those `time_open` fields be removed? They are showing **wrong** data.

**Comment by zhquan** [comment]
Hi @sanacl,

> I did not know about time_to_close_days. I may use it :)

You are already using it in your screenshot.
![maniphest_time_to_close_day](https://user-images.githubusercontent.com/5637233/87425886-b3e8a000-c5de-11ea-8be4-68d48f153912.png)

> The thing about time_open_days_enrich is that it is not calculated as the diff between creation_date and now, it is calculated between creation_date and the latest change enriched. So if a ticket was open on January 1st and the last change (a tag was added) was done in January 2nd, the value for time_open_days_enrich will be 1.

As I said at https://github.com/chaoss/grimoirelab-elk/issues/910#issuecomment-655980862 the value `time_open_days_enrich` is calculated as the diff between `creation_date` and `now`
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/phabricator.py#L314

As I said at https://github.com/chaoss/grimoirelab-elk/issues/910#issuecomment-656562876 the `time_to_close_days` is calculated between `creation_date` and `updated_date` (https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/phabricator.py#L309). In your image, the task was closed on March 19th but the last update was on July 7th. So this field `time_to_close_days` will calculate with July 7th. And on that image, you are using the field `time_to_close_days`.

I think the field `time_open_days_enrich` is wrong due to it means lifespan and not time open days. We should add this change to calculate the real `time_open_days_enrich` at https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/phabricator.py#L314
```
if eitem['status'] not in [TASK_OPEN_STATUS, 'Spite', 'Stalled']:
    eitem['time_open_days_enrich'] = get_time_diff_days(eitem['creation_date'],
                                                        eitem['modification_date'])
```

And create a scripted field (painless_opendays) to calculate the time when the task is still open as

```
if (doc.containsKey('status') && (doc['status'].value != 'Open' || doc['status'].value != 'Spite' || doc['status'].value != 'Stalled')) {
  return doc['time_open_days_enrich'].value;
} else {
  return Duration.between(LocalDateTime.ofInstant(Instant.ofEpochMilli(doc['grimoire_creation_date'].value.millis), ZoneId.of('Z')), LocalDateTime.ofInstant(Instant.ofEpochMilli(new Date().getTime()), ZoneId.of('Z'))).toMinutes()/1440.0;
}
```
Very similar commented at https://github.com/chaoss/grimoirelab-elk/issues/910#issuecomment-655980862

Best,
Quan

**Comment by sanacl** [comment]
Thanks @zhquan for you detailed comments. I got lost with some of the fields and I'm creating a bigger misunderstanding so please allow me to start from scratch with this comment. Please let me know whether you think we should update the description of the ticket or create a new one.

---

I'm studying a Maniphest ticket with id 15268 in my data set. According to Phabricator this ticket was:
* created on June 12th 2020
* marked as resolved on June 18th 2020 (it tooks 6 days to be closed)
* it last update (with a tag/project) was done on July 7th (25 days after being created)

The data I get from the BAP instance is:
![image](https://user-images.githubusercontent.com/326719/87528418-c837a600-c68d-11ea-82b6-7e3ff5a8b549.png)

* `time_to_close_days`: 25.03
* `time_open_days_enrich`: 25.06
* `timeopen_days`: 25.06

Based on the name of the fields I understand that:
* `time_to_close_days` contains the time from ticket creation to ticket resolution (to any of the closed statuses)
* `time_open_days_enrich` and `timeopen_days` contain the time from:
** ticket creation to ticket resolution to any of the closed statuses, for closed tickets
** ticket creation to now, for open tickets

Based on @zhquan comments I understand:
* `time_to_close_days` contains the time from ticket creation to last modification, even if that modification was done after ticket was closed. This is a bug in my opinion.
* `time_open_days_enrich` contains the time from ticket creation to enrichment time, even if the ticket was closed long ago. This is another bug in my opinion
* `timeopen_days` contains same information than `time_open_days_enrich`, no idea about the difference. It looks like they share the same bug.

So, I do think either the data stored in those 3 fields is incorrect or the field name should be renamed to avoid confusion.

**Comment by zhquan** [comment]
Here is my proposal:
- `time_to_close_days`: time from ticket creation to ticket close (`resolved`, `wontfix`, `invalid`, `spite`, `duplicate`)
- `painless_timeopen_days` (new field): 
  - If the ticket is close is the same as `time_to_close_days`
  - if the ticket is still open diff between `creaton_date` and now
- `close_date` (new field): date the ticket was closed
- `time_open_days_enrich` removed
- `timeopen_days`: removed

Or keep the old names to avoid issues with the visualizations/dashboards

When the ticket is closed
![image](https://user-images.githubusercontent.com/5637233/87552792-6f2e3900-c6b2-11ea-860f-f11b5fe66571.png)
When the ticket is still open
![image](https://user-images.githubusercontent.com/5637233/87554834-f11f6180-c6b4-11ea-9904-8898b54ae79e.png)

WDYT @sanacl?

**Comment by sanacl** [comment]
@zhquan It like it very much.

Minor comment: The only thing I would change is the name of "close_date". If the first word must be a noum and not a verb, it should be "closing_date". But I am not aware of the naming of the indexes so maybe I'm talking nonsense. In that case drop this comment ;)

**Comment by zhquan** [comment]
To be aligned with the rest of the enriched backends:
- `painless_timeopen_days` -> `painless_delay`
- `close_date` -> `closed_at`

PR available at https://github.com/chaoss/grimoirelab-elk/pull/917 to fix `time_to_close_days` field
PR available at https://github.com/chaoss/grimoirelab-sigils/pull/462 to update visualizations/dashboards

**Comment by sduenas** [comment]
This is already done. Closing it.
