### ISSUE TITLE
Tautology in Elk's description

### ISSUE THREAD

**Issue by stevenkolawole** [chaoss/grimoirelab-elk#972]
I was going through the source code while reading the README.md alongside when I stumbled upon this;

> Bugzilla: each document corresponds to a single issue.
> Bugzillarest: each document corresponds to a single issue.

[https://github.com/chaoss/grimoirelab-elk/blob/master/README.md#enriched-data](https://github.com/chaoss/grimoirelab-elk/blob/master/README.md#enriched-data).

Both `Bugzilla` and `Bugzillarest` documents refer to the same definition. 

Is there a mixup somewhere or do they genuinely mean the same thing? If they both mean the same thing, wouldn't one of them suffice, instead of having two documents with the same meaning?

**cc**: @vchrombie

**Comment by sduenas** [comment]
Maybe we can reword that. **Bugzilla** and **Bugzillarest** refer to the backends/APIs used to retrieve that data. Both were obtained from `bugzilla` datasource but the structure of data - not the content - is different.

Data from Bugzilla was obtained using CGIs calls and returns data in XML format. Later, it's converted to JSON. On the other hand. Bugzillarest data is obtained using Bugzilla's REST API and the data is stored in JSON format.

**Comment by SteveKola** [comment]
Alright. It is much clearer now. Thank you. 😄 

The rewording, is it something I could do?

**Comment by sduenas** [comment]
Sure! Go ahead.
