### ISSUE TITLE
Handle GitHub issue assignees during enrichment phase

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-elk#99]
The latest version of GitHub backend in Perceval includes on its items the assignees of each issue. GrimoireELK should handle these assignees to enrich items with these data.

**Comment by valeriocos** [comment]
Fixed it with https://github.com/chaoss/grimoirelab-elk/commit/0cebccbd55ccec55b52f7d82dcb0694fabc5e397
