### ISSUE TITLE
`no_update` is not transmitted to the perceval backend.

### ISSUE THREAD

**Issue by xiao623** [chaoss/grimoirelab-elk#996]
From https://github.com/chaoss/grimoirelab-perceval/blob/8ed4fb18055b5cb0fe6fc67c80ab50b285e306df/perceval/backends/core/git.py#L375
```
        exgroup_fetch.add_argument('--no-update', dest='no_update',
```
we can set `no-update` to fetch all commits without updating the repository.

However, even if I set `no-update = true` in `setup.cfg` when I used sirmordred module, the parameter wasn't transmitted to the perceval backend.

I think the reason is that the `no-update` is hidden in `grimoire_elk.elk.feed_backend`.
https://github.com/chaoss/grimoirelab-elk/blob/00b346623d8f3f0b4de901d25a0ef28e79a02545/grimoire_elk/elk.py#L81

Here, `no-update` is true which we set in parsed_args.

https://github.com/chaoss/grimoirelab-elk/blob/00b346623d8f3f0b4de901d25a0ef28e79a02545/grimoire_elk/elk.py#L148-L160

Here, `no-update` is not transmitted when we call `ocean_backend.feed(**params)`.

And then, in the method `ocean_backend.feed`, we lost the `no-update` so that we would use the default value `false` for `no-update` in `Git.fetch` forever.

**Comment by zhquan** [comment]
@xiao623 - Thank you for reporting this issue. You are right, the field `no_update` is not transmitted to `perceval`.
